/*
Solution to Project Euler's problem number 2
https://projecteuler.net/problem=2

Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
*/

package main

import "fmt"

func main() {
	a := 1
	b := 2
	c := 0
	sum := 2
	for {
		c = a + b

		if c > 4000000 {
			break
		}

		if c%2 == 0 {
			sum += c
		}

		a = b
		b = c
	}
	fmt.Print("The sum is: ", sum)
}

// http://twitter.com/
// G'day sir @Todd_McLeod !
// https://github.com/edsonbrusque/udemyTraining/blob/master/16_exercises/07/main.go
